package br.com.ipt.arche2.similarity;

public class Constantes {
	public static final String SIMILARIDADE_LOCAL_SEMANTICA_W1 = "SIMILARIDADE_LOCAL_SEMANTICA_W1";
	public static final String SIMILARIDADE_LOCAL_SEMANTICA_W2 = "SIMILARIDADE_LOCAL_SEMANTICA_W2";
	
	public static final String SIMILARIDADE_LOCAL_MEDIDAS_W1 = "SIMILARIDADE_LOCAL_MEDIDAS_W1";
	public static final String SIMILARIDADE_LOCAL_MEDIDAS_W2 = "SIMILARIDADE_LOCAL_MEDIDAS_W2";
	public static final String SIMILARIDADE_LOCAL_MEDIDAS_W3 = "SIMILARIDADE_LOCAL_MEDIDAS_W3";

	public static final String SIMILARIDADE_GLOBAL_W1 = "SIMILARIDADE_GLOBAL_W1";
	public static final String SIMILARIDADE_GLOBAL_W2 = "SIMILARIDADE_GLOBAL_W2";
	
	public static final String SIMILARIDADE_MINIMA_CASOS = "SIMILARIDADE_MINIMA_CASOS";
}
